version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: rag-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: ragdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: